name: Render Credits file

on:
  push:
    branches:
      - '*'

jobs:
  render_credits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: yarn install

      - name: Generate credits
        run: yarn run generate

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: credits
          path: |
            ./credits
